# Generated by Django 5.2 on 2025-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('inventory_count', models.IntegerField()),
                ('source_platform', models.CharField(max_length=100)),
            ],
        ),
    ]
